#cloud-config
#verify if wheel already has good enough permissions
users:
  - default
  - name: gw-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrShBmIKGEHG1xTAixLKNZcNXkpmXlsUz9bkV/ArizLorivjOW0LvyjdawBZUlcey+o/tRECV2HnRaALRMSeCI5PzcQ0q65VoWs7Vuv8P0sItaJ1qJFupSOPxF99WfENQ1TZ6p/vNb6VxoRoQkbX2LrsSTsEqfizGIUL21TjbnEj+HcIgiennH28FyJ4GCJjozvymFNZnS71y9Or5DWvkD88RYDlRvcsS0jUN+5Y/5KsDHRaGmjqX79b284RyXF01JpWVuO0q9pUD+5qt7b1Pr/SSMWL4d2aMHRDXBplYwFm+Fj6g1bjYz+/WcVsY1O9AvDMcawx7uIHTX3rYYq61cE1V6JO1FI3kj2QSaP/UPTkDU0JqxZ+nLPtfHUML1gRrZRxXUs9Kwyf4z1jE2OpzVYkvAHhwbGzk4zmBtkNcln9RDAGMia+oBhdNfUjxRJdNgIpK7YeWyQRDgOZ+7eBUP5fuInodHBHdHHOvYlU5E77lWREjI1gyMsbGPHVDkEKEEhcgPWarqsz4Nr+S6XzbqlePq7yZhVRcZH8jbh/NBDo7nPLnleptjqZzWi6pD3LQWnwt5g6+/yDOO0xuexHG6jzFt+YC6gpztXJg4k5xTw6peYvTg6j57M7A3+lQgsqHaHVE060eG+gYpGp3v4EI4+jBu8lsApAoABDY5boI6Bw==
  - name: packer
    inactive: true
write_files:
- path: /etc/sysctl.d/90-kubelet.conf
  owner: root:root  
  permissions: '0644'
  content: |
    vm.overcommit_memory = 1
    vm.panic_on_oom = 0
    kernel.panic = 10
    kernel.panic_on_oops = 1
    kernel.keys.root_maxkeys = 1000000
    kernel.keys.root_maxbytes = 25000000
- path: /usr/local/bin/rancher-bootstrap.sh
  permissions: '0700'
  content: |
    #!/bin/bash -x

    PRIVATE_IP=$(curl -H Metadata:True "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json" | jq '.network.interface[0].ipv4.ipAddress[0].privateIpAddress')
    PUBLIC_IP=$(curl -H Metadata:True "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json" | jq '.network.interface[0].ipv4.ipAddress[0].publicIpAddress')
    IS_WORKER=$(curl -H Metadata:True "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json" | jq .compute.tags | grep role:worker | wc -l)
    IS_MASTER=$(curl -H Metadata:True "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json" | jq .compute.tags | grep role:master | wc -l)
    IS_BOTH=$(curl -H Metadata:True "http://169.254.169.254/metadata/instance?api-version=2019-03-11&format=json" | jq .compute.tags | grep role:both | wc -l)
    
    if [ $IS_MASTER = 1 ]; then
      K8S_ROLES="--etcd --controlplane"
    fi
    if [ $IS_WORKER = 1 ]; then
      K8S_ROLES="--worker"
    fi
    if [ $IS_BOTH = 1 ]; then
      K8S_ROLES="--roles"
    fi

    echo "IS_MASTER=$IS_MASTER"
    echo "IS_WORKER=$IS_WORKER"
    echo "IS_BOTH=$IS_BOTH"
    echo "K8S_ROLES=$K8S_ROLES"
    #docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:<RANCHER_VERSION> --server https://<RANCHER_URL> --token <RANCHER_TOKEN> --ca-checksum <RANCHER_CA_CHECKSUM> --address ${PUBLIC_IP} --internal-address ${PRIVATE_IP} ${K8S_ROLES}
runcmd:
 - yum update
 - curl https://stedolan.github.io/jq/download/linux64/jq > /usr/bin/jq && chmod +x /usr/bin/jq
 - curl -sL https://releases.rancher.com/install-docker/19.03.sh | sh
 - usermod -aG docker azure-user
 - /usr/local/bin/rancher-bootstrap.sh