#cloud-config
#verify if wheel already has good enough permissions
users:
  - default
  - name: gw-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrShBmIKGEHG1xTAixLKNZcNXkpmXlsUz9bkV/ArizLorivjOW0LvyjdawBZUlcey+o/tRECV2HnRaALRMSeCI5PzcQ0q65VoWs7Vuv8P0sItaJ1qJFupSOPxF99WfENQ1TZ6p/vNb6VxoRoQkbX2LrsSTsEqfizGIUL21TjbnEj+HcIgiennH28FyJ4GCJjozvymFNZnS71y9Or5DWvkD88RYDlRvcsS0jUN+5Y/5KsDHRaGmjqX79b284RyXF01JpWVuO0q9pUD+5qt7b1Pr/SSMWL4d2aMHRDXBplYwFm+Fj6g1bjYz+/WcVsY1O9AvDMcawx7uIHTX3rYYq61cE1V6JO1FI3kj2QSaP/UPTkDU0JqxZ+nLPtfHUML1gRrZRxXUs9Kwyf4z1jE2OpzVYkvAHhwbGzk4zmBtkNcln9RDAGMia+oBhdNfUjxRJdNgIpK7YeWyQRDgOZ+7eBUP5fuInodHBHdHHOvYlU5E77lWREjI1gyMsbGPHVDkEKEEhcgPWarqsz4Nr+S6XzbqlePq7yZhVRcZH8jbh/NBDo7nPLnleptjqZzWi6pD3LQWnwt5g6+/yDOO0xuexHG6jzFt+YC6gpztXJg4k5xTw6peYvTg6j57M7A3+lQgsqHaHVE060eG+gYpGp3v4EI4+jBu8lsApAoABDY5boI6Bw==
  - name: packer
    inactive: true
runcmd:
 - systemctl stop firewalld
 - systemctl disable firewalld
 - yum -y install iptables-services
 - systemctl enable iptables
 - systemctl enable ip6tables
 - systemctl start iptables
 - systemctl start ip6tables
 - iptables -F
